In [1]:
import pandas as pd

In [5]:
df = pd.read_json("myfile.json")

df.describe()

       CustomerID
count   24.000000
mean     2.000000
std      0.834058
min      1.000000
25%      1.000000
50%      2.000000
75%      3.000000
max      3.000000

In [6]:
df.head(10)

   CustomerID     Name                Email
0           1    Alice    alice@example.com
1           2      Bob      bob@example.com
2           3  Charlie  charlie@example.com
3           1    Alice    alice@example.com
4           2      Bob      bob@example.com
5           3  Charlie  charlie@example.com
6           1    Alice    alice@example.com
7           2      Bob      bob@example.com
8           3  Charlie  charlie@example.com
9           1    Alice    alice@example.com

In [7]:
df = df.fillna(0)

In [9]:
df.iloc[0]

CustomerID                    1
Name                      Alice
Email         alice@example.com
Name: 0, dtype: object

In [10]:
df1 = pd.read_xml("emp.xml")
df1

      id            Name           Description  Status
0  OP001    StartService    Starts the service  Active
1  OP002     StopService     Stops the service  Active
2  OP003  RestartService  Restarts the service  Active

In [1]:
import pandas as pd
df2 = pd.read_parquet("sample-users.parquet")
df2.describe()

ImportError: Unable to find a usable engine; tried using: 'pyarrow', 'fastparquet'.
A suitable version of pyarrow or fastparquet is required for parquet support.
Trying to import the above resulted in these errors:
 - Missing optional dependency 'pyarrow'. pyarrow is required for parquet support. Use pip or conda to install pyarrow.
 - Missing optional dependency 'fastparquet'. fastparquet is required for parquet support. Use pip or conda to install fastparquet.

In [2]:
%pip install pyarrow

Defaulting to user installation because normal site-packages is not writeable
Collecting pyarrow
  Downloading pyarrow-25.0.1-cp310-cp310-win_amd64.whl (27.8 MB)
Installing collected packages: pyarrow
Successfully installed pyarrow-25.0.1
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.2.4; however, version 26.2.1 is available.
You should consider upgrading via the 'c:\Program Files\Python\python.exe -m pip install --upgrade pip' command.

In [1]:
import pandas as pd
df2 = pd.read_parquet("sample-users.parquet")
df2.describe()

           user_id          age      balance                 signup_date
count  1000.000000  1000.000000  1000.000000                        1000
mean    500.500000    46.672000  5082.639590  2022-10-23 10:45:07.200000
min       1.000000    18.000000    34.730000         2020-01-01 00:00:00
25%     250.750000    32.000000  2742.807500         2021-06-03 06:00:00
50%     500.500000    47.000000  5097.490000         2022-12-07 00:00:00
75%     750.250000    61.000000  7534.075000         2024-02-14 12:00:00
max    1000.000000    75.000000  9995.950000         2025-06-22 00:00:00
std     288.819436    16.946374  2859.475186                         NaN

In [4]:
df4 = pd.read_orc("orc_test1_sample.orc")
df4

,boolean1,byte1,short1,int1,long1,float1,double1,bytes1,string1,middle,list,map
0,False,1,1024,65536,9223372036854775807,1.0,-15.0,b'\x00\x01\x02\x03\x04',hi,"{'list': [{'int1': 1, 'string1': 'bye'}, {'int...","[{'int1': 3, 'string1': 'good'}, {'int1': 4, '...",[]
1,True,100,2048,65536,9223372036854775807,2.0,-5.0,b'',bye,"{'list': [{'int1': 1, 'string1': 'bye'}, {'int...","[{'int1': 100000000, 'string1': 'cat'}, {'int1...","[(chani, {'int1': 5, 'string1': 'chani'}), (ma..."

In [ ]:
df6 = pd.read_html("index.html")
df6

[    Employee ID Employee Name Department Designation  Salary
 0          1001    Employee 1         IT    Engineer   51000
 1          1002    Employee 2         HR     Analyst   52000
 2          1003    Employee 3    Finance     Manager   53000
 3          1004    Employee 4      Sales        Lead   54000
 4          1005    Employee 5  Marketing   Executive   55000
 ..          ...           ...        ...         ...     ...
 95         1096   Employee 96         IT    Engineer  146000
 96         1097   Employee 97         HR     Analyst  147000
 97         1098   Employee 98    Finance     Manager  148000
 98         1099   Employee 99      Sales        Lead  149000
 99         1100  Employee 100  Marketing   Executive  150000

 [100 rows x 5 columns]]

In [7]:
import pandas as pd
empdf = pd.read_excel("employees.xlsx")

empdf.dtypes

First Name                   object
Gender                       object
Start Date           datetime64[ns]
Last Login Time              object
Salary                        int64
Bonus %                     float64
Senior Management           float64
Team                         object
dtype: object

In [5]:
import pandas as pd

shipDf = pd.read_csv("dirty_data_ship.csv")

shipDf.dtypes
shipDf.head(10)

,Order ID,consumer_first_class,consumer_same_day,consumer_second_class,consumer_standard_class,consumer_total,corporate_first_class,corporate_same_day,corporate_second_class,corporate_standard_class,corporate_total,home_office_first_class,home_office_same_day,home_office_second_class,home_office_standard_class,home_office_total
0,CA-2011-100293,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91.056,91.056
1,CA-2011-100706,NaN,NaN,129.44,NaN,129.44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CA-2011-100895,NaN,NaN,NaN,605.47,605.47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CA-2011-100916,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,788.860,788.860,NaN,NaN,NaN,NaN,NaN
4,CA-2011-101266,NaN,NaN,13.36,NaN,13.36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,CA-2011-101560,NaN,NaN,NaN,NaN,NaN,NaN,NaN,542.34,NaN,542.340,NaN,NaN,NaN,NaN,NaN
6,CA-2011-101770,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.869,1.869,NaN,NaN,NaN,NaN,NaN
7,CA-2011-102274,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,865.500,865.500,NaN,NaN,NaN,NaN,NaN
8,CA-2011-102673,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1044.440,1044.440,NaN,NaN,NaN,NaN,NaN
9,CA-2011-102988,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4251.92,NaN,4251.920,NaN,NaN,NaN,NaN,NaN

In [7]:

print(shipDf.shape)
print(shipDf.info())
print(shipDf.isna().sum())

(823, 16)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Order ID                    823 non-null    object
 1   consumer_first_class        73 non-null     float64
 2   consumer_same_day           29 non-null     float64
 3   consumer_second_class       92 non-null     float64
 4   consumer_standard_class     254 non-null    float64
 5   consumer_total              445 non-null    float64
 6   corporate_first_class       41 non-null     float64
 7   corporate_same_day          6 non-null      float64
 8   corporate_second_class      51 non-null     float64
 9   corporate_standard_class    153 non-null    float64
 10  corporate_total             248 non-null    float64
 11  home_office_first_class     13 non-null     float64
 12  home_office_same_day        7 non-null      float64
 13  home_office_second_class    24 non-null     float64
 14  home_office_standard_class  91 non-null     float64
 15  home_office_total           132 non-null    float64
dtypes: float64(15), object(1)
memory usage: 103.0+ KB
None
Order ID                        0
consumer_first_class          750
consumer_same_day             794
consumer_second_class         731
consumer_standard_class       569
consumer_total                378
corporate_first_class         782
corporate_same_day            817
corporate_second_class        772
corporate_standard_class      670
corporate_total               575
home_office_first_class       810
home_office_same_day          816
home_office_second_class      799
home_office_standard_class    732
home_office_total             691
dtype: int64

In [50]:
import pandas as pd
df = pd.read_csv("dirty_data_ship.csv")
df.columns
s1 = df.melt(id_vars=['Order ID'],var_name='Segment',value_name='Sales')
s1

             Order ID               Segment       Sales
0      CA-2011-100293  consumer_first_class         NaN
1      CA-2011-100706  consumer_first_class         NaN
2      CA-2011-100895  consumer_first_class         NaN
3      CA-2011-100916  consumer_first_class         NaN
4      CA-2011-101266  consumer_first_class         NaN
...               ...                   ...         ...
12340  US-2014-166611     home_office_total         NaN
12341  US-2014-167920     home_office_total         NaN
12342  US-2014-168116     home_office_total         NaN
12343  US-2014-168690     home_office_total         NaN
12344     Grand Total     home_office_total  74255.0015

[12345 rows x 3 columns]

In [51]:
s1 = s1.dropna(subset=["Sales"])
s1

             Order ID               Segment       Sales
11     CA-2011-103366  consumer_first_class    149.9500
20     CA-2011-109043  consumer_first_class    243.6000
29     CA-2011-113166  consumer_first_class      9.5680
51     CA-2011-124023  consumer_first_class      8.9600
63     CA-2011-130155  consumer_first_class     34.2000
...               ...                   ...         ...
12324  US-2014-148768     home_office_total     71.9760
12331  US-2014-156083     home_office_total      9.6640
12333  US-2014-159205     home_office_total    732.9300
12335  US-2014-162558     home_office_total   2437.6720
12344     Grand Total     home_office_total  74255.0015

[1659 rows x 3 columns]

In [52]:
s1['Segment'] = (
    s1['Segment']
    .str.replace('_', ' ')
    .str.title()
)
s1

C:\Users\Y856864\AppData\Local\Temp\ipykernel_36880\712646529.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s1['Segment'] = (

             Order ID               Segment       Sales
11     CA-2011-103366  Consumer First Class    149.9500
20     CA-2011-109043  Consumer First Class    243.6000
29     CA-2011-113166  Consumer First Class      9.5680
51     CA-2011-124023  Consumer First Class      8.9600
63     CA-2011-130155  Consumer First Class     34.2000
...               ...                   ...         ...
12324  US-2014-148768     Home Office Total     71.9760
12331  US-2014-156083     Home Office Total      9.6640
12333  US-2014-159205     Home Office Total    732.9300
12335  US-2014-162558     Home Office Total   2437.6720
12344     Grand Total     Home Office Total  74255.0015

[1659 rows x 3 columns]

In [53]:
s1 = s1.rename(
    columns={
        'Order ID':'OrderID'
    }
)
print(s1.head(20))
# s1.to_csv("Clean_Ship_data.csv" , index = False)

            OrderID               Segment     Sales
11   CA-2011-103366  Consumer First Class   149.950
20   CA-2011-109043  Consumer First Class   243.600
29   CA-2011-113166  Consumer First Class     9.568
51   CA-2011-124023  Consumer First Class     8.960
63   CA-2011-130155  Consumer First Class    34.200
76   CA-2011-136861  Consumer First Class    31.984
104  CA-2011-153927  Consumer First Class   286.650
113  CA-2011-157784  Consumer First Class   514.030
119  CA-2011-160094  Consumer First Class  1000.950
128  CA-2011-164749  Consumer First Class     9.912
134  CA-2011-166730  Consumer First Class    39.128
146  CA-2012-102722  Consumer First Class   106.500
147  CA-2012-102778  Consumer First Class    18.176
179  CA-2012-117828  Consumer First Class   194.320
204  CA-2012-130218  Consumer First Class    59.480
206  CA-2012-132318  Consumer First Class   182.910
220  CA-2012-137974  Consumer First Class  2298.900
222  CA-2012-138625  Consumer First Class   197.720
226  CA-2012-141327  Consumer First Class   440.144
241  CA-2012-149300  Consumer First Class    32.985

In [54]:
# s1[['Segment', 'Ship Mode']] = s1['Segment'].str.split(' ', n=1, expand=True)

# # Rearrange columns if you want Ship Mode right after Segment
# s1 = s1[['OrderID', 'Segment', 'Ship Mode', 'Sales']]

# s1
# Force the split result to have exactly 2 columns
split_df = s1['Segment'].str.split(' ', n=1, expand=True).reindex(columns=[0, 1])
# print(split_df)
# Assign safely
s1['Segment'] = split_df[0]
s1['Ship Mode'] = split_df[1]

s1

              OrderID   Segment       Sales     Ship Mode
11     CA-2011-103366  Consumer    149.9500   First Class
20     CA-2011-109043  Consumer    243.6000   First Class
29     CA-2011-113166  Consumer      9.5680   First Class
51     CA-2011-124023  Consumer      8.9600   First Class
63     CA-2011-130155  Consumer     34.2000   First Class
...               ...       ...         ...           ...
12324  US-2014-148768      Home     71.9760  Office Total
12331  US-2014-156083      Home      9.6640  Office Total
12333  US-2014-159205      Home    732.9300  Office Total
12335  US-2014-162558      Home   2437.6720  Office Total
12344     Grand Total      Home  74255.0015  Office Total

[1659 rows x 4 columns]